name: robu
description: "Robotics Club of Brac University......"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.8
  share_plus: ^10.1.0
  provider: ^6.1.2
  youtube_player_flutter: ^9.1.1
  http: ^1.2.2
  flutter_launcher_icons: ^0.14.1
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  dart_jsonwebtoken: ^2.14.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

#This is for launcher icon or app icon
############################################
#flutter_icons:
#  ios: true
#  android: true
#  image_path_ios: 'assets/app_icon/icon.png'
#  image_path_android: 'assets/app_icon/icon.png'
#  adaptive_icon_background: '#ffffff'
#  adaptive_icon_foreground: 'assets/app_icon/icon.png'
flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: '#ffffff'
  image_path_android: 'assets/app_icon/icon.png'
  image_path_ios: 'assets/app_icon/icon.png'
  adaptive_icon_foreground: 'assets/app_icon/icon.png'
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  ###########################################


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/banner/
   - assets/dev/
   - assets/panel24/
   - assets/projects/
   - assets/ui/
   - assets/app_icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
